<?php

/*
    -- Session
    --- Session Is Stored On The Server
    --- Session Store Only A User Key In Cookie To Know It's You
    --- The Key Is Generated By PHP Engine So It's Almost Imposible To Guess
    --- You Need To Add It Before Any Output
*/

// first of all we need to start the session
// if we didn't start the session we don't have access to use super global "$_SESSION"
session_start();

$_SESSION['Name'] = "Abdallah";
$_SESSION['Id'] = "7510";

echo "<pre>";
print_r($_SESSION);
echo "</pre>";

// Now We Can Use This Information In Any Place

echo "<a href= " ."Test.php" . ">Test</a>";
?>